---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Wait for target to become reachable
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - name: Install and Configurate UFW
      include_role:
        name: ufw
      vars:
        state: enabled
        rules: "{{ terraform_config.ufw_rules }}"
      tags:
        - ufw
