---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Wait for target to become reachable
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - name: Intall Tmux
      include_role:
        name: tmux
      vars:
        username: "{{ terraform_config.user_name }}"
      tags:
        - tmux

    - name: Install Node Exporter service
      include_role:
        name: node_exporter
      tags:
        - node_exporter

    - name: Install Go Lang
      include_role:
        name: golang
      tags:
        - golang

    - name: Install Terraform
      include_role:
        name: terraform
      tags:
        - terraform

    - name: Install Mosh
      include_role:
        name: mosh
      tags:
        - mosh

    - name: Install Python3
      include_role:
        name: python3
      tags:
        - python3

    - name: Install Oh My ZSH
      include_role:
        name: oh_my_zsh
      vars:
        username: "{{ terraform_config.user_name }}"
      tags:
        - oh_my_zsh

    - name: Install Docker
      include_role:
        name: docker
        apply:
          become: yes
          tags:
            always
      vars:
        docker__users: ["{{ terraform_config.user_name }}"]
      tags:
        - docker
        - install