---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Wait for target to become reachable
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:    
    - name: Pre-flight check
      include_role:
        name: pre_flight_check
      tags:
        - preflight
        - check
    
    - name: Add user
      include_role:
        name: user
      vars:
        username: "{{ terraform_config.user_name }}"
        password: "{{ terraform_config.user_password }}"
        passwordless_sudo: yes
        user_groups: "sudo"
        authorized_keys: "{{ terraform_config.bastion_user_authorized_keys }}"
      tags:
        - user

    - name: Install and Configurate SSH
      vars:
        access_port: "{{ terraform_config.bastion_ssh_port }}"
        root_acc_access: no
        password_auth: no
        set_ssh_ansible_user: "{{ terraform_config.user_name }}"
      include_role:
        name: ssh
      tags:
        - ssh
