---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Wait for target to become reachable
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:    
    - name: Pre-flight check
      include_role:
        name: pre_flight_check
      tags:
        - preflight
        - check
    
    - name: Add user
      include_role:
        name: user
      vars:
        username: "{{ terraform_config.user_name }}"
        password: "{{ terraform_config.user_password }}"
        passwordless_sudo: yes
        user_groups: "sudo"
        authorized_keys: "{{ terraform_config.bastion_user_authorized_keys }}"
      tags:
        - user

    - name: Install and Configurate SSH
      vars:
        access_port: "{{ bastion_ssh_port }}"
        root_acc_access: no
        password_auth: no
        set_ssh_ansible_user: "{{ default_user.name }}"
      include_role:
        name: ssh
      tags:
        - ssh
    
    - name: Intall Tmux
      include_role:
        name: tmux
      vars:
        username: "{{ terraform_config.user_name }}"
      tags:
        - tmux

    - name: Install Node Exporter service
      include_role:
        name: node_exporter
      tags:
        - node_exporter

    - name: Install Go Lang
      include_role:
        name: golang
      tags:
        - golang

    - name: Install and Configurate UFW
      include_role:
        name: ufw
      vars:
        state: enabled
        rules: "{{ terraform_config.ufw_rules }}"
      tags:
        - ufw

    - name: Install Terraform
      include_role:
        name: terraform
      tags:
        - terraform
    
    - name: Install Mosh
      include_role:
        name: mosh
      tags:
        - mosh
    
    - name: Install Python3
      include_role:
        name: python3
      tags:
        - python3

    - name: Install Oh My ZSH
      include_role:
        name: oh_my_zsh
      vars:
        username: "{{ terraform_config.user_name }}"
      tags:
        - oh_my_zsh

    - name: Install Docker
      include_role:
        name: docker
        apply:
          become: yes
          tags:
            always
      vars:
        docker__users: ["{{ terraform_config.user_name }}"]
      tags:
        - docker
        - install