---
- name: Create directories
  become: yes
  file: 
    path: "{{ item }}"
    state: "directory"
    mode: 0775
  with_items:
    - "{{ data_folder }}"
  tags:
    - docker
    - container
    - mysql

- name: Backup mysql databases
  shell: "docker exec -e MYSQL_PWD={{ password }} mysql /usr/bin/mysqldump -u {{ username }} {{ item }} > {{ data_folder }}/{{ item }}_$(date '+%Y.%m.%d-%H.%M.%S').sql"
  with_items: "{{ dbs }}"
  when: dbs | length > 0
  tags:
    - docker
    - container
    - mysql