---
- name: Install `python-minimal`
  raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  register: output
  changed_when: output.stdout != ""
  tags:
    - always

- name: Install `python-setup-tools`
  raw: test -e /usr/bin/pip || (apt -y update && apt install -y python-pip python-dev build-essential python-setuptools)
  register: output
  changed_when: output.stdout != ""
  tags:
    - always

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # One day
  tags:
    - always

- name: Install `pip` repositories
  package:
    name: ['epel-release','centos-release-scl']
    state: latest
  when: ansible_distribution == 'CentOS'
  tags:
    - always

- name: Install `pip`
  package:
    name: ['python-pip','rh-python36']
    state: latest
  when: ansible_distribution == 'CentOS'
  tags: install
  tags:
    - always

- name: Install `pip`
  apt:
    pkg: ['python3-pip']
    state: latest
  tags:
    - always

- name: Installing python modules
  become: false
  pip:
    name: 
      - docker
      - pip
      - ansible
      - docker-compose
  tags:
    - always