- name: Install Python3 packages
  become: true
  apt:
    name:
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - virtualenv
  when: pyenv == None

- name: Install pyenv dependencies
  become: true
  apt:
    pkg:
      - curl
      - gcc
      - git
      - libbz2-dev
      - libreadline-dev
      - libssl-dev
      - libsqlite3-dev
      - make
      - zlib1g-dev
    state: present
  when: pyenv != None