---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400 # One day
      tags:
        - preflight
        - check

    - name: Install Home Assistant
      include_role:
        name: home_assistant