# Registers LXC container's IP addresses in Consul KV Store
# Invoked by Terraform on PVE Node after container created
# Requires consul server running
# Example: ansible-playbook -i '<pve node>,' ./lxc/lxc_register.yml -e 'ansible_user=root' -e 'container_id=105'
---
- hosts: all
  gather_facts: no
  pre_tasks:
    - name: Include variables
      vars:
        file: prod.yml
      include_role:
        name: vars
      tags:
        - always
  tasks:
    - name: Install `pip`
      become: yes
      package:
        name: python3-pip
        state: present
      tags:
        - pip
    
    - name: Installing python modules
      become: true
      pip:
        name: 
          - python-consul
          - requests
      tags:
        - pip

    - name: Wait for container
      wait_for:
        path: /sys/fs/cgroup/pids/lxc/{{ container_id }}/pids.events

    - name: Get Container IP Address
      command: "lxc-info -n {{ container_id }} -iH"
      register: container_info
    
    - debug:
        msg: "{{ container_info }}"
          
    - name: Create Key in KV Store
      consul_kv:
        host: "{{ consul.default.host }}"
        port: "{{ consul.default.port }}"
        scheme: "{{ consul.default.scheme }}"
        key: proxmox/{{ pve_node }}/lxc/{{ container_id }}/ipv4_address/{{ item.0 }}
        value: "{{ item.1 }}"
        state: present
      with_indexed_items: "{{ container_info.stdout_lines }}"