---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - block:
      - name: Update and upgrade apt packages
        become: true
        apt:
          upgrade: "yes"
          update_cache: "yes"
          cache_valid_time: 86400 # One day

      - name: Install Plex Media Server
        include_role:
          name: plex
        vars:
          plex_username: "{{ terraform_config.plex_username }}"
          plex_password: "{{ terraform_config.plex_password }}"
          plex_server_name: "{{ terraform_config.plex_server_name }}"
      
      - name: Stop Plex server
        service:
          name: plexmediaserver
          state: stopped

      - name: Install Sub Zero plugin
        include_role:
          name: plex_plugin_sub_zero

      - name: Install Trakttv plugin
        include_role:
          name: plex_plugin_trakttv

      - name: Install Webtools plugin
        include_role:
          name: plex_plugin_webtools
    
      always:
        - name: Start Plex server
          service:
            name: plexmediaserver
            state: started
      
      become: yes
