---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
  - name: Run Pre-tasks
    include_role:
      name: pre_tasks
    tags:
      - always
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400 # One day
      tags:
        - preflight
        - check
  
    - name: Install additional packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libsasl2-dev
        - gcc
        - python-dev
        - python3-pip
      tags:
        - install

    - name: Installing python modules
      become: true
      pip:
        name: 
          - docker
          - pip
          - localstack[full]
          - docker-compose
      tags:
        - preflight
        - check
  
    - name: Install Docker
      include_role:
        name: docker
        apply:
          become: yes
          tags:
            always
      tags:
        - docker
        - install

    - name: Start Local Stack container
      include_role:
        name: docker_localstack
      tags:
        - local_stack