---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Run Pre-tasks
      include_role:
        name: pre_tasks
      tags:
        - always
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400 # One day
    
    - set_fact:
        consul_data_dir: /var/consul/data

    - name: Remove Peers file
      file:
        path: "{{ consul_data_dir }}/{{ item }}"
        state: absent
      with_items:
        - serf/local.keyring
        - raft/peers.info
        - raft/peers.json

    - name: Install Consul Server
      include_role:
        name: consul
      vars:
        data_dir: "{{ consul_data_dir }}"
        encrypt_key: "{{ terraform_config.consul.default.encrypt_key }}"
        domain_name: "{{ terraform_config.domain.name }}"
        datacenter_name: "{{ terraform_config.consul.default.data_center }}"
        client_addr: "{{ ansible_default_ipv4.address }}"
        bootstrap: true
        server: true
        ui: true
        dns_config: true
        ports: true
        ports_dns: 53
        recursors: [
          "{{ terraform_config.domain.dns_servers[0] }}"
        ]
        start_join: [
          "{{ ansible_default_ipv4.address }}"
        ]
