---
- name: Install tmux
  become: yes
  apt:
    pkg: ['tmux', 'xclip']
    state: latest
  tags: 
    - tmux

- name: Cloning gpakosz/.tmux.git
  git:
    repo=https://github.com/gpakosz/.tmux.git
    dest=/home/{{ username }}/.tmux
    force=yes
  tags: 
    - tmux

- name: Link .tmux.conf
  file:
    src: "/home/{{ username }}/.tmux/.tmux.conf"
    dest: "/home/{{ username }}/.tmux.conf"
    state: link
  tags: 
    - tmux

- name: Copy .tmux.conf.local
  copy:
    src: .tmux.conf.local
    dest: /home/{{ username }}/.tmux.conf.local
  tags: 
    - tmux