apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ .Values.name | quote }}
  namespace: {{ .Values.namespace | quote }}
spec:
  secretName: {{ .Values.secretName | quote }}
  dnsNames:
    {{- with .Values.dnsNames }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  uriSANs:
    {{- with .Values.uriSANs }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  ipAddresses:
    {{- with .Values.ipAddresses }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  issuerRef:
    name: {{ .Values.issuerRef.name }}
    kind: {{ .Values.issuerRef.kind }}
    group: {{ .Values.issuerRef.group }}