---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
  - name: Run Pre-tasks
    include_role:
      name: pre_tasks
    tags:
      - always
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 86400 # One day
      tags:
        - preflight
        - check

    - name: Install `pip`
      become: yes
      apt:
        pkg: ['python3-pip']
        state: latest
      tags:
        - preflight
        - check

    - name: Installing python modules
      become: true
      pip:
        name: 
          - docker
          - pip
          - ansible
          - docker-compose
      tags:
        - preflight
        - check
  
    - name: Install curl
      package:
        name: curl
        state: present
      tags:
        - install
  
    - name: Install Docker
      include_role:
        name: docker
        apply:
          become: yes
          tags:
            always
      tags:
        - docker
        - install

    # TODO: Replace this role with non-docker version
    # Compile artifacts inside LXC container rather than provision container
    - name: Start Bitwarden_rs container
      include_role:
        name: docker_bitwarden_rs
      vars:
        SIGNUPS_ALLOWED: "false"
      tags:
        - bitwarden_rs