---
- name: Add  user "{{ username }}"
  become: yes
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: "{{ user_groups }}"
    append: no
    remove: "{{ remove }}"
    shell: "{{ shell }}"
    generate_ssh_key: "{{ generate_ssh_key }}"
  tags:
    - user
    - create

- name: Add authorized key for "{{ username }}"
  become: yes
  authorized_key:
    user: "{{ username }}"
    state: "{{ item.state | d('present') }}"
    key: "{{ item.path }}"
  with_items: "{{ authorized_keys }}"
  tags:
    - user
    - keys

- name: Add user "{{ username }}" to /etc/sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    regexp: "{{ username }} ALL" 
    line: "{{ username }} ALL=(ALL) ALL" 
    state: "{{ sudoers | ternary('present', 'absent') }}"
    create: yes
  tags: 
    - user
    - sudoers

- name: Allow sudo commands without password for "{{ username }}"
  become: yes
  lineinfile:
    dest: /etc/sudoers 
    regexp: "{{ username }} ALL=(ALL) NOPASSWD: ALL" 
    line: "{{ username }}  ALL=(ALL) NOPASSWD: ALL" 
    state: "{{ passwordless_sudo | ternary('present', 'absent') }}"
    create: yes
  tags:
    - user
    - passwordless