---
# Default Configuration

## Ansible configuration
ansible_python_interpreter: /usr/bin/python3
ansible_distribution: ubuntu
ansible_distribution_release: bionic
ansible_python:
  version:
    major: 3

## User
user__name: deploy
user__email:

## Docker (https://github.com/nickjj/ansible-docker)
docker__state: present
docker__edition: ce
docker__channel: ['stable']
docker__version: '19.03.5'
docker__compose_version: '1.25.4'
docker__pip_docker_state: present
docker__pip_docker_compose_state: 'present'
docker__users: ["{{ ansible_env.SUDO_USER | d('root') }}", "{{ user__name }}"] # Try to use the sudo user by default, but fall back to root.

## Swap
swap_file_path: /swapfile
# Use any of the following suffixes
# c=1
# w=2
# b=512
# kB=1000
# K=1024
# MB=1000*1000
# M=1024*1024
# xM=M
# GB=1000*1000*1000
# G=1024*1024*1024
swap_file_size: 4G
swappiness: 1