---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
  - name: Run Pre-tasks
    include_role:
      name: pre_tasks
    tags:
      - always
  tasks:
    - name: Install Traefik Service
      include_role:
        name: traefik
        apply:
          tags:
            - always
      vars:
        systemd_user: root
        systemd_group: root
        traefik_environment: "{{ terraform_config.traefik_environment }}"
        traefik_cli_options: "{{ terraform_config.traefik_cli_options }}"

    # - name: Install Consul Agent
    #   include_role:
    #     name: consul
    #   vars:
    #     encrypt_key: "{{ consul.default.encrypt_key }}"
    #     domain_name: "{{ domain.name }}"
    #     datacenter_name: "{{ consul.default.data_center }}"
    #     start_join: "{{ consul[consul.default.data_center].servers | map(attribute='host') | list }}"