---
- hosts: ax3
  gather_facts: no
  pre_tasks:
    - name: Include variables
      vars:
        file: prod.yml
      include_role:
        name: vars
      tags:
        - always
  tasks:
    - name: Pre-flight check
      include_role:
        name: pre_flight_check
      tags:
        - preflight
        - check

    - name: Create Minio Container
      vars:
          folders: "{{ ax3.minio.mount_folders }}"
          access_key: "{{ ax3.minio.access_key }}"
          secret_key: "{{ ax3.minio.secret_key }}"
          virtual_host: "{{ ax3.minio.virtual_host }}"
          letsencrypt_host: "{{ ax3.minio.letsencrypt_host }}"
          published_ports: "{{ ax3.minio.published_ports }}"
          networks:
            - name: cloudbox
      include_role:
        name: docker_minio
      tags:
        - docker
        - container
        - minio
