- name: Get latest kubectl release information
  uri:
    url: "https://storage.googleapis.com/kubernetes-release/release/stable.txt"
    method: GET
    status_code: 200
    body_format: raw
    return_content: true
  register: kubectl_stable_response
  tags:
    - kubectl

- name: Delete kubectl executable
  become: yes
  file: path=/usr/local/bin/kubectl state=absent
  tags:
    - kubectl

- name: Get latest kubectl release
  become: yes
  uri:
    url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_stable_response.content[:-1] }}/bin/linux/amd64/kubectl"
    method: GET
    status_code: 200
    dest: "/usr/local/bin/kubectl"
    mode: +x
  tags:
    - kubectl