---
- name: Create directories
  become: yes
  file: 
    path: "{{ item }}"
    state: "directory"
    mode: 0777
  with_items:
    - "{{ data_folder }}/{{ container_name }}"
    - "{{ data_folder }}/{{ container_name }}/data/config"
  tags:
    - docker
    - container
    - code_server

- name: Create and start container
  docker_container:
    name: "{{ container_name }}"
    recreate: "{{ recreate }}"
    image: "{{ image }}"
    env:
      PASSWORD: "{{ password }}"
      SUDO_PASSWORD: "{{ sudo_password }}"
      LETSENCRYPT_HOST: "{{ letsencrypt_host }}"
      VIRTUAL_HOST: "{{ virtual_host }}"
    hostname: "{{ hostname }}"
    published_ports: "{{ published_ports }}"
    volumes:
      - "{{ data_folder }}/{{ container_name }}/data/config:/config"
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    state: "{{ state }}"
    networks: "{{ networks }}"
  tags:
    - docker
    - container
    - code_server