---
- name: Setup SSH
  block:
    - name: Root Account SSH access
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin {{ root_acc_access | ternary('yes', 'no', 'no') }}"
        state: present

    - name: Password authentication
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication {{ password_auth | ternary('yes', 'no', 'no') }}"
        state: present

    - name: Setup alternate SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port {{ access_port }}"

    - name: Add firewall rule
      ufw:
        { rule: allow, port: "{{ access_port }}", proto: tcp }
      when: firewall_rules == True

    - name: Set old SSH port variable
      set_fact:
        old_ansible_port: "{{ ansible_port | d('22') }}"

    - name: Restart SSH
      systemd:
        name: sshd
        daemon_reload: yes
        state: restarted

    - name: Set SSH port variable
      set_fact:
        ansible_port: "{{ access_port }}"

    - debug:
        msg: "{{ set_ssh_ansible_user }} {{ access_port }}"

    - name: Set SSH user variable
      set_fact:
        ansible_user: "{{ set_ssh_ansible_user }}"

    - name: Set SSH user variable
      set_fact:
        ansible_ssh_user: "{{ set_ssh_ansible_user }}"

    - name: Wait for system to become reachable
      wait_for_connection:
        delay: 10
        timeout: 600

    - name: Remove firewall rule
      ufw:
        { rule: allow, port: "{{ old_ansible_port }}", proto: tcp, delete: yes }
      when: firewall_rules == True and access_port != old_ansible_port 
  become: yes
  tags:
    - ssh