---
- hosts: all
  gather_facts: no
  become: yes
  pre_tasks:
    - name: Include variables
      vars:
        file: prod.yml
      include_role:
        name: vars
      tags:
        - always
  tasks:
    - name: Install Pihole
      include_role:
        name: pihole
      vars:
        webui_password: "{{ lxc.pihole.webui_password }}"
        dns_servers: "{{ lxc.pihole.network.dns_servers }}"
        conditional_forwarding: "{{ lxc.pihole.conditional_forwarding }}"
        conditional_forwarding_ip: "{{ lxc.pihole.conditional_forwarding_ip }}"
        conditional_forwarding_domain: "{{ lxc.pihole.conditional_forwarding_domain }}"
        conditional_forwarding_reverse: "{{ lxc.pihole.conditional_forwarding_reverse }}"
        extra_block_lists:
          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all-but-whatsapp
            enabled: true

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/facebook/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/localized
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/google/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/microsoft/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/amazon/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/apple/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/cloudflare/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/mozilla/all
            enabled: false

          - url: https://raw.githubusercontent.com/jmdugan/blocklists/master/corporations/pinterest/all
            enabled: false

          - url: https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/hosts.txt
            enabled: true

          - url: https://gitlab.com/ookangzheng/dbl-oisd-nl/raw/master/dbl.txt
            enabled: true

          - url: http://sysctl.org/cameleon/hosts
            enabled: true
            
          - url: https://mirror1.malwaredomains.com/files/justdomains
            enabled: true

          - url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
            enabled: true

          - url: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
            enabled: true

          - url: https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
            enabled: true

          - url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
            enabled: true
      tags:
        - lxc
        - pihole

    - name: Install Consul Agent
      include_role:
        name: consul
      vars:
        encrypt_key: "{{ consul.default.encrypt_key }}"
        domain_name: "{{ domain.name }}"
        datacenter_name: "{{ consul.default.data_center }}"
        start_join: "{{ consul[consul.default.data_center].servers | map(attribute='host') | list }}"
      tags:
        - consul